In [1]:
import numpy as np
import pandas as pd

In [20]:
data = pd.read_csv('Ecommerce Purchases')

In [21]:
data

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

**1 Display 10 rows of the Dataset**

In [22]:
data.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

**2 check last 10 rows of data set**

In [23]:
data.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

**3 check datatype of column**

In [28]:
data.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

** 4 check null values in data set**

In [31]:
data.isnull().sum()

np.int64(0)

** 5 how many rows and column are there in data set**

In [33]:
len(data.columns)

14

In [34]:
len(data)

10000

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [37]:
data.shape

(10000, 14)

In [38]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [39]:
data['Purchase Price'].max()

99.99

In [40]:
data['Purchase Price'].min()

0.0

**7 average  purchase  prive**

In [41]:
data['Purchase Price'].mean()

np.float64(50.347302)

**8 how many peope have  frence fr as theie language**

In [42]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [46]:
len(data[data['Language']=='fr'])

1097

In [47]:
data[data['Language']=='fr'].count()

Address             1097
Lot                 1097
AM or PM            1097
Browser Info        1097
Company             1097
Credit Card         1097
CC Exp Date         1097
CC Security Code    1097
CC Provider         1097
Email               1097
Job                 1097
IP Address          1097
Language            1097
Purchase Price      1097
dtype: int64

**9 job title ehich contains engineer**

In [49]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [55]:
len(data[data['Job'].str.contains('engineer',case=False)])

984

**10. Find The Email of the person with the following IP Address: 132.207.160.22**

In [56]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [58]:
data[data['IP Address']=='132.207.160.22']['Email']

2    amymiller@morales-harrison.com
Name: Email, dtype: object

**11. How many People have Mastercard as their Credit Card Provider and made a purchase above 50?**

In [60]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [64]:
data[(data['CC Provider']=='Mastercard') & (data['Purchase Price']>50)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
31,USNS Alvarado\nFPO AA 27052-1231,26 Lh,PM,Opera/8.84.(X11; Linux i686; sl-SI) Presto/2.9...,Nicholson Group,4614997834548,03/22,909,Mastercard,ashley12@hotmail.com,Sales executive,94.176.142.201,en,94.14
35,"93392 Webb Gardens Apt. 220\nLaurabury, AR 999...",37 om,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Mora Ltd,6011049630969815,09/16,367,Mastercard,hgonzalez@mcdowell.com,"Lecturer, further education",216.23.95.40,zh,97.46
90,"431 Bowen Lights\nFergusonborough, MH 01362",31 tG,AM,Mozilla/5.0 (Windows NT 5.2; it-IT; rv:1.9.1.2...,Copeland-Lee,639032576097,06/18,868,Mastercard,nrogers@brown.com,"Teacher, English as a foreign language",153.188.13.203,es,78.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9948,"95544 Johnson Isle Suite 939\nMichaelberg, RI ...",91 bW,AM,Opera/8.36.(X11; Linux x86_64; sl-SI) Presto/2...,Fox-Peterson,4762924304307,03/17,567,Mastercard,haleybenjamin@gmail.com,Structural engineer,120.36.140.58,en,71.89
9954,"051 Samantha Wells Apt. 328\nScottborough, OR ...",11 vG,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_2...,"Mendoza, Zimmerman and Reilly",30232295374907,05/21,762,Mastercard,brownamy@perkins.com,"Presenter, broadcasting",61.97.84.101,it,87.15
9981,"087 Larson Roads Apt. 587\nRicestad, WI 98077-...",95 Kw,AM,Opera/9.63.(Windows NT 5.01; en-US) Presto/2.9...,"Ortiz, Schultz and Adams",4690863684605,01/19,695,Mastercard,laurenbennett@richards.com,Environmental education officer,106.21.237.73,pt,63.61
9987,"2754 Klein Mission\nJohnsonview, PA 64925-9624",65 Fg,PM,Opera/9.26.(Windows CE; sl-SI) Presto/2.9.188 ...,Curtis LLC,180027305702263,12/24,865,Mastercard,denisehamilton@novak.biz,Primary school teacher,164.39.190.217,es,60.83

 **Find the email of the person with the following Credit Card Number: 4664825258997302**

In [66]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [69]:
data[data['Credit Card']==4664825258997302]['Email']

9992    bberry@wright.net
Name: Email, dtype: object

**13. How many people purchase during the AM and how many people purchase during PM?**

In [70]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [72]:
data['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

**14. How many people have a credit card that expires in 2020?**

In [75]:
data.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [76]:
data['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

In [80]:
def fun():
    cnt = 0
    for i in data['CC Exp Date']:
        if i.split('/')[1] == '20':
            cnt += 1
    print(cnt)

In [81]:
fun()

988

In [84]:
data[data['CC Exp Date'].apply(lambda x:x[3:]=='20')].count()

Address             988
Lot                 988
AM or PM            988
Browser Info        988
Company             988
Credit Card         988
CC Exp Date         988
CC Security Code    988
CC Provider         988
Email               988
Job                 988
IP Address          988
Language            988
Purchase Price      988
dtype: int64

**15. What are the top 5 most popular email providers (e.g. gmail.com, yahoo.com, etc...)A**

In [86]:
list=[]
for email in data['Email']:
    list.append(email.split('@')[1])

In [87]:
list

['yahoo.com',
 'reed.com',
 'morales-harrison.com',
 'olson-robinson.info',
 'gmail.com',
 'gmail.com',
 'yahoo.com',
 'parks.info',
 'rasmussen.com',
 'hunt-huerta.com',
 'hotmail.com',
 'coleman.com',
 'hotmail.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'wilson.com',
 'hall.com',
 'yahoo.com',
 'gmail.com',
 'smith.info',
 'hotmail.com',
 'gmail.com',
 'gardner-meadows.com',
 'yahoo.com',
 'mooney.com',
 'gmail.com',
 'hotmail.com',
 'yahoo.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'atkinson.com',
 'yahoo.com',
 'carey-davis.com',
 'mcdowell.com',
 'walsh.com',
 'frederick.info',
 'boyd-english.org',
 'wells-carlson.info',
 'dickerson.com',
 'yahoo.com',
 'gmail.com',
 'martinez-thomas.com',
 'yahoo.com',
 'chambers.com',
 'gmail.com',
 'glenn.org',
 'allen.com',
 'gmail.com',
 'obrien.org',
 'cook-castillo.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'yahoo.com',
 'lawrence-warren.biz',
 'morris.com',
 'howe.com',
 'walton.org',
 'jones.biz',
 'gmail.com',
 'simmons-gutierrez.org',
 'yahoo.com',
 'gardner-anderson.com',
 'gmail.com',
 'hotmail.com',
 'green.com',
 'wallace-moore.info',
 'wiley.net',
 'rodgers-morris.biz',
 'johnson.info',
 'hotmail.com',
 'gmail.com',
 'reyes.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'beasley-murphy.net',
 'donovan-brown.biz',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'weber-williams.com',
 'yahoo.com',
 'smith-brown.info',
 'fleming.info',
 'yahoo.com',
 'gmail.com',
 'brown.com',
 'hotmail.com',
 'harrison-brown.info',
 'kim.biz',
 'watkins.com',
 'thomas.net',
 'yahoo.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'cochran.com',
 'gmail.com',
 'yahoo.com',
 'jackson-johnson.biz',
 'woods-nunez.biz',
 'price.com',
 'gmail.com',
 'white.com',
 'hotmail.com',
 'lowe.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'allen-kennedy.org',
 'hotmail.com',
 'nelson.com',
 'long.net',
 'hotmail.com',
 'yahoo.com',
 'cervantes-smith.net',
 'silva-cohen.com',
 'wilson-wright.biz',
 'allen.com',
 'yahoo.com',
 'aguirre.com',
 'scott.net',
 'nelson.com',
 'gmail.com',
 'gmail.com',
 'henderson-peterson.org',
 'yahoo.com',
 'yahoo.com',
 'james.biz',
 'stewart.org',
 'martinez.com',
 'yahoo.com',
 'yahoo.com',
 'wright.com',
 'lopez.net',
 'yahoo.com',
 'carlson.net',
 'bean-mcdaniel.com',
 'bennett.com',
 'mosley-brown.com',
 'yahoo.com',
 'fisher.com',
 'guerrero.net',
 'cardenas.com',
 'yahoo.com',
 'smith-conner.org',
 'sherman-perry.org',
 'matthews.com',
 'gmail.com',
 'valenzuela-mccarty.org',
 'wagner.com',
 'williams.info',
 'yahoo.com',
 'gmail.com',
 'beck-hickman.com',
 'hotmail.com',
 'perez-acosta.com',
 'dunn.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'collier.com',
 'yahoo.com',
 'hood.com',
 'yahoo.com',
 'taylor-moore.net',
 'gmail.com',
 'gmail.com',
 'sanchez-chambers.net',
 'gmail.com',
 'flynn-callahan.com',
 'yahoo.com',
 'good.com',
 'scott.com',
 'french-richards.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'wright.com',
 'davenport-zimmerman.com',
 'gray.com',
 'hotmail.com',
 'hotmail.com',
 'olson.com',
 'shaw.com',
 'murray-jones.com',
 'cruz.com',
 'alexander-villegas.com',
 'brown.net',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'delacruz.biz',
 'beasley.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'griffith.com',
 'hotmail.com',
 'smith.org',
 'green-lee.com',
 'hotmail.com',
 'bauer.com',
 'kane.com',
 'mullins-fletcher.com',
 'gmail.com',
 'knight.com',
 'gmail.com',
 'newman.com',
 'bass.com',
 'hotmail.com',
 'spence-browning.com',
 'caldwell-strickland.com',
 'bush.org',
 'yahoo.com',
 'jones-white.com',
 'suarez.com',
 'elliott.com',
 'sanchez.com',
 'yahoo.com',
 'mitchell-daugherty.com',
 'foster.org',
 'griffin.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'robinson.org',
 'smith-bates.com',
 'yahoo.com',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'ellis.com',
 'hotmail.com',
 'murray.com',
 'gmail.com',
 'yahoo.com',
 'moss.info',
 'yahoo.com',
 'weaver.com',
 'hill-bentley.net',
 'gmail.com',
 'rivera-bishop.com',
 'hotmail.com',
 'west-phillips.info',
 'hotmail.com',
 'gmail.com',
 'phillips-johnson.org',
 'gmail.com',
 'lambert.com',
 'hotmail.com',
 'reyes.net',
 'wade-butler.org',
 'henderson.com',
 'spence.com',
 'hotmail.com',
 'powell.net',
 'johnson.biz',
 'castro.org',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'summers-boyd.com',
 'carter.com',
 'yahoo.com',
 'hotmail.com',
 'brooks.net',
 'obrien.com',
 'espinoza.org',
 'yahoo.com',
 'hicks.com',
 'yahoo.com',
 'gmail.com',
 'flynn.info',
 'harvey-hunt.com',
 'acevedo-pena.biz',
 'daniels.com',
 'gmail.com',
 'roberts.com',
 'kim.biz',
 'yahoo.com',
 'gmail.com',
 'davis.com',
 'mills.com',
 'butler-lozano.com',
 'martinez.net',
 'carter-adams.biz',
 'gmail.com',
 'edwards.com',
 'smith-butler.net',
 'yahoo.com',
 'nguyen.org',
 'yahoo.com',
 'yahoo.com',
 'brown.com',
 'shaw.net',
 'hotmail.com',
 'smith.biz',
 'hotmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'lopez.com',
 'mccormick-kirby.com',
 'sellers.com',
 'smith.net',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'hawkins-green.net',
 'york-atkins.com',
 'hotmail.com',
 'yahoo.com',
 'green.com',
 'gmail.com',
 'garcia.com',
 'cardenas.net',
 'yahoo.com',
 'kerr-wilson.com',
 'gmail.com',
 'richardson.com',
 'yahoo.com',
 'hart.com',
 'yahoo.com',
 'anthony.com',
 'griffin-thomas.com',
 'hotmail.com',
 'moore.com',
 'ross.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'lee.net',
 'gmail.com',
 'hotmail.com',
 'graham.com',
 'yahoo.com',
 'jackson.com',
 'yahoo.com',
 'hotmail.com',
 'frey-ward.com',
 'sanford.com',
 'gmail.com',
 'moreno.com',
 'carson.net',
 'hotmail.com',
 'blackburn-lucero.com',
 'jackson.net',
 'kelley-arnold.com',
 'osborne.info',
 'valenzuela.com',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'rodriguez.com',
 'hotmail.com',
 'stevenson-curry.biz',
 'gmail.com',
 'hotmail.com',
 'davis-mcdonald.com',
 'jones.net',
 'hotmail.com',
 'henry.org',
 'yahoo.com',
 'yahoo.com',
 'gmail.com',
 'pugh.com',
 'ballard.com',
 'thompson.com',
 'gmail.com',
 'brown.net',
 'bates-wood.biz',
 'jordan-pierce.com',
 'gmail.com',
 'yahoo.com',
 'velasquez.net',
 'figueroa.info',
 'hotmail.com',
 'hotmail.com',
 'osborne.info',
 'sanchez.com',
 'merritt-york.com',
 'yahoo.com',
 'johnson-white.biz',
 'gonzalez.org',
 'miller.com',
 'yahoo.com',
 'rhodes.com',
 'yahoo.com',
 'hotmail.com',
 'potts-rose.net',
 'hotmail.com',
 'moore.info',
 'yahoo.com',
 'barrera.org',
 'page.com',
 'gmail.com',
 'vaughn.com',
 'moore.org',
 'martinez-williams.net',
 'gmail.com',
 'mcclure.biz',
 'carr.com',
 'yahoo.com',
 'gonzalez.com',
 'hotmail.com',
 'williams.com',
 'thomas.biz',
 'andrews.com',
 'herrera-miller.biz',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'allen.org',
 'thomas.com',
 'fuller-johnson.com',
 'robinson.com',
 'armstrong.biz',
 'yahoo.com',
 'yahoo.com',
 'robinson.com',
 'yahoo.com',
 'hotmail.com',
 'rodriguez-hernandez.com',
 'gmail.com',
 'foster.net',
 'dalton.net',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'castro-whitaker.net',
 'hill.biz',
 'stein-cox.com',
 'vargas-brown.com',
 'melton-duke.com',
 'yahoo.com',
 'yahoo.com',
 'lopez.com',
 'moran.com',
 'brown.com',
 'hotmail.com',
 'guzman-davis.com',
 'gmail.com',
 'allen.com',
 'gonzalez.net',
 'cox.com',
 'sanders.org',
 'yahoo.com',
 'jensen.info',
 'yahoo.com',
 'hotmail.com',
 'reed.com',
 'meyer-palmer.org',
 'hotmail.com',
 'kramer.com',
 'peters-green.com',
 'perez.info',
 'berry-davis.com',
 'hotmail.com',
 'johnson.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'murray.info',
 'hotmail.com',
 'lindsey.net',
 'roberts.net',
 'gmail.com',
 'yahoo.com',
 'smith-ford.biz',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'fritz.com',
 'gmail.com',
 'clark-simpson.com',
 'gmail.com',
 'hotmail.com',
 'patton.com',
 'oconnor-dixon.com',
 'yahoo.com',
 'yahoo.com',
 'murray.net',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'moore-robinson.com',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'yahoo.com',
 'moore-lutz.com',
 'deleon-ortega.org',
 'page.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'livingston.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'wright.net',
 'hotmail.com',
 'gmail.com',
 'schwartz.info',
 'cook.com',
 'richardson-flores.com',
 'brown-bean.com',
 'wilkinson.com',
 'richardson.biz',
 'figueroa-jones.com',
 'yahoo.com',
 'hotmail.com',
 'choi-morris.com',
 'gmail.com',
 'lee.com',
 'torres.biz',
 'owen-gross.com',
 'hotmail.com',
 'deleon.com',
 'yahoo.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'clark.com',
 'baker.com',
 'smith-nunez.info',
 'tyler.com',
 'yahoo.com',
 'aguilar-nelson.com',
 'holder.com',
 'livingston-smith.biz',
 'smith-reid.com',
 'hotmail.com',
 'gmail.com',
 'rodriguez.com',
 'yahoo.com',
 'hurst.com',
 'smith-collins.biz',
 'hotmail.com',
 'wright.com',
 'gmail.com',
 'hotmail.com',
 'tran-mccoy.org',
 'mclaughlin.com',
 'wilson.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'barnes.com',
 'yahoo.com',
 'yahoo.com',
 'browning.com',
 'yahoo.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'palmer-mckee.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'yahoo.com',
 'johnson-oliver.net',
 'carpenter.info',
 'brown-wilson.net',
 'martinez-malone.com',
 'chung.com',
 'alvarez.com',
 'perez.com',
 'gmail.com',
 'jones.com',
 'aguilar.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'garrison-woodard.com',
 'hotmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'adams.com',
 'reid.com',
 'gmail.com',
 'meza-jackson.org',
 'curtis.com',
 'marquez-castillo.biz',
 'rangel.net',
 'lewis-brown.net',
 'hotmail.com',
 'hotmail.com',
 'copeland.org',
 'yahoo.com',
 'fritz-gray.com',
 'carson.com',
 'hotmail.com',
 'hotmail.com',
 'haynes.com',
 'gmail.com',
 'stafford.com',
 'hotmail.com',
 'reid.com',
 'cruz.biz',
 'ballard-myers.info',
 'yahoo.com',
 'hernandez-nielsen.com',
 'yahoo.com',
 'wagner.com',
 'hotmail.com',
 'yahoo.com',
 'moore.com',
 'russell.com',
 'hughes.com',
 'gmail.com',
 'martin-chavez.com',
 'smith.com',
 'terrell.biz',
 'hotmail.com',
 'gmail.com',
 'gmail.com',
 'davis.com',
 'steele.net',
 'rose.info',
 'long.com',
 'hotmail.com',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'russell.com',
 'yahoo.com',
 'short.biz',
 'gmail.com',
 'yahoo.com',
 'roach.com',
 'vaughn-sullivan.biz',
 'dean.com',
 'mills.com',
 'yahoo.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'walker-morales.com',
 'malone.com',
 'fernandez.com',
 'jackson-pitts.com',
 'yahoo.com',
 'morris.biz',
 'anderson-duke.com',
 'yahoo.com',
 'yahoo.com',
 'hernandez.biz',
 'harris.com',
 'gmail.com',
 'murphy.org',
 'richards.org',
 'gmail.com',
 'gonzales-anderson.com',
 'davenport-garcia.com',
 'hull.info',
 'gmail.com',
 'atkins.biz',
 'martin.com',
 'nguyen-smith.net',
 'bailey.net',
 'black.org',
 'hotmail.com',
 'sanford-lopez.com',
 'kelly.biz',
 'hotmail.com',
 'garcia-pugh.biz',
 'cox.com',
 'yahoo.com',
 'yahoo.com',
 'anderson-werner.biz',
 'hotmail.com',
 'browning-yu.com',
 'yahoo.com',
 'lopez-kelly.com',
 'fernandez-bell.com',
 'campbell.info',
 'gmail.com',
 'manning.org',
 'rollins.com',
 'johnson-long.biz',
 'flynn-williams.com',
 'hotmail.com',
 'winters.info',
 'gmail.com',
 'gmail.com',
 'graham-green.net',
 'hotmail.com',
 'ballard.net',
 'long.com',
 'meyer.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'gmail.com',
 'hotmail.com',
 'roberts.com',
 'hotmail.com',
 'hart-reynolds.com',
 'yahoo.com',
 'jimenez.biz',
 'turner-hall.net',
 'yahoo.com',
 'gmail.com',
 'haynes-pollard.info',
 'hotmail.com',
 'yahoo.com',
 'clay.net',
 'yahoo.com',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'foster-travis.biz',
 'gmail.com',
 'hotmail.com',
 'price.org',
 'hughes.com',
 'chen-cantu.net',
 'santana.com',
 'long.org',
 'hotmail.com',
 'hotmail.com',
 'smith.net',
 'beard-franco.com',
 'marshall-johnson.net',
 'sherman.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'boone-barton.com',
 'velez.com',
 'gmail.com',
 'johnson-grant.net',
 'hotmail.com',
 'gomez.info',
 'hopkins.biz',
 'silva.com',
 'gmail.com',
 'thomas.org',
 'armstrong-adkins.biz',
 'hotmail.com',
 'ritter.com',
 'holmes-jones.com',
 'walter.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'rodriguez.biz',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'yahoo.com',
 'hotmail.com',
 'sellers-perez.net',
 'reese-mcintosh.com',
 'jackson.org',
 'medina-reyes.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'duncan-garcia.com',
 'hotmail.com',
 'webster.com',
 'myers.com',
 'gmail.com',
 'yahoo.com',
 'yahoo.com',
 'gray-mejia.com',
 'clark-garcia.org',
 'wright-walton.com',
 'gmail.com',
 'yahoo.com',
 'smith-harrison.com',
 'hotmail.com',
 'hotmail.com',
 'martin.info',
 'hotmail.com',
 'gmail.com',
 'johnson-schmidt.com',
 'hall-stephens.net',
 'mora.info',
 'coleman.com',
 'hotmail.com',
 'jones-morgan.org',
 'hotmail.com',
 'yahoo.com',
 'robbins-mcdonald.com',
 'gmail.com',
 'hotmail.com',
 'knight.biz',
 'simmons-rasmussen.com',
 'molina.org',
 'smith.biz',
 'jones.com',
 'anderson-thompson.com',
 'taylor.org',
 'gmail.com',
 'yahoo.com',
 'carroll.com',
 'logan.net',
 'best.com',
 'yahoo.com',
 'yahoo.com',
 'gill-flores.com',
 'hotmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'guerrero.com',
 'hotmail.com',
 'yahoo.com',
 'gardner.com',
 'hotmail.com',
 'reed-gonzalez.com',
 'yahoo.com',
 'white.com',
 'hotmail.com',
 'gmail.com',
 'davis.com',
 'clay.net',
 'yahoo.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'yahoo.com',
 'williams.biz',
 'pearson.com',
 'gmail.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'luna-hancock.info',
 'little-branch.info',
 'murphy-berry.com',
 'marshall.com',
 'alvarez.com',
 'rivas-glover.com',
 'sloan.com',
 'gonzalez.com',
 'rivera.org',
 'hotmail.com',
 'moore-martinez.biz',
 'gmail.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'gmail.com',
 'hotmail.com',
 'morrison-smith.com',
 'gmail.com',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'hotmail.com',
 'torres.com',
 'hotmail.com',
 'brown.net',
 'hotmail.com',
 'yahoo.com',
 'caldwell.net',
 'yahoo.com',
 'gmail.com',
 'hotmail.com',
 'gmail.com',
 'gmail.com',
 'summers.info',
 'hotmail.com',
 'yahoo.com',
 'rios.com',
 'yahoo.com',
 'gross.com',
 'thompson.com',
 'weber.org',
 'gmail.com',
 'yahoo.com',
 'hotmail.com',
 'andrews.biz',
 'gmail.com',
 'johnson-dean.com',
 'gmail.com',
 'hotmail.com',
 'yahoo.com',
 'galloway.com',
 'coleman-williams.net',
 'rodriguez.org',
 'stein-hayes.com',
 'hotmail.com',
 'hahn-roberts.com',
 'green.org',
 'hernandez-finley.net',
 'dunlap.net',
 'butler-thompson.net',
 'stone.com',
 'melendez-decker.net',
 'yahoo.com',
 'knapp.info',
 'gonzalez.info',
 'hotmail.com',
 'guerrero.info',
 'burton.com',
 'underwood-jenkins.org',
 'brown.com',
 'yahoo.com',
 'hotmail.com',
 'anderson.net',
 'hotmail.com',
 'hotmail.com',
 'berry.com',
 'rodriguez-yang.com',
 'payne-bell.info',
 'guerrero-shah.com',
 'hotmail.com',
 'hotmail.com',
 'riley.com',
 'gonzalez-gamble.org',
 'craig.com',
 'hotmail.com',
 'lee.org',
 'hotmail.com',
 'haynes-nguyen.com',
 'parker.com',
 'gmail.com',
 'hotmail.com',
 'reeves-cole.biz',
 'hotmail.com',
 'barnes.com',
 'anderson-fleming.biz',
 'myers.biz',
 'henderson.net',
 'goodwin.com',
 'bass-sullivan.info',
 'yahoo.com',
 'hotmail.com',
 'whitney.org',
 'hotmail.com',
 'aguilar.com',
 'gmail.com',
 'gmail.com',
 'brooks.com',
 'hotmail.com',
 'miller.info',
 'stone.net',
 'hotmail.com',
 'hotmail.com',
 'hotmail.com',
 'silva-cox.com',
 'hill.net',
 'curtis.com',
 'hotmail.com',
 'hotmail.com',
 'dorsey.org',
 'velazquez.com',
 'yahoo.com',
 'cox-cole.com',
 'duarte.com',
 'gmail.com',
 'hotmail.com',
 'knight.com',
 'hotmail.com',
 'king-blanchard.com',
 ...]

In [88]:
data['temp']=list

In [90]:
data.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,temp
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com

In [92]:
data['temp'].value_counts().head()

temp
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

In [ ]:
data['Em']